### ISSUE TITLE
Error using scoreRankingGO and prioritizedGOTerms. Cellular Components.

### ISSUE THREAD

**Issue by CeballosGene** [cran/GOxploreR#2]
I'm using GOxploreR version 1.2.3.
I'm having these errors when trying to obtain scores and prioritize Cellular Components GO Terms:
```
all<-c("GO:0031974","GO:0070013","GO:0043233","GO:0005622","GO:0005654","GO:0043229","GO:0043231")
scoreRankingGO(goterm = all, domain = "CC", plot = TRUE)
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘Ontology’ for signature ‘"logical"’ 

```
prioritizedGOTerms(lst = all, organism = "Human", domain = "CC")
```
Error in prioritizedGOTerms(lst = all, organism = "Human", domain = "CC") : 
  object 'CC' not found

I hope you can help me with this issue! Thanks

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by CeballosGene** [comment]
OK! Thanks, sorry for the mistake.
